theme: jekyll-theme-tactile
title: Giesela
permalink: /:title
url: https://gieseladev.github.io/Giesela
google_analytics: UA-100028815-1
favicon: https://gieseladev.github.io/Giesela/assets/favicon.png
