theme: jekyll-theme-tactile
title: Giesela
url: https://siku2.github.io/MusicBot
google_analytics: UA-100028815-1
permalink: /:title
favicon: https://github.com/siku2/MusicBot/blob/master/docs/assets/favicon.PNG
